Repository GSG-G8/ca-wiki, pull requests merged in 2020-04, with the labels that each got.

#43 handle Delete cohort route
  .eslintrc.json
  server/controllers/index.js
  server/controllers/routes/admin/cohort/deleteCohort.js
  server/controllers/routes/admin/cohort/index.js
  server/controllers/routes/admin/index.js
  server/database/queries/cohort/deleteCohort.js
  server/database/queries/cohort/index.js
  server/database/queries/index.js
  test/index.test.js
Labels: Approved, Backend

#46 24 post project
  server/controllers/index.js
  server/controllers/middlewares/errorHandle/error.js
  server/controllers/middlewares/errorHandle/index.js
  server/controllers/routes/admin/index.js
  server/controllers/routes/admin/project/addProject.js
  server/controllers/routes/admin/project/index.js
  server/database/queries/index.js
  server/database/queries/project/addProject.js
  server/database/queries/project/index.js
  server/validation/index.js
  server/validation/projectSchema.js
  test/index.test.js
Labels: Awaiting Review, Backend

#41 GET cohort by id
  server/controllers/index.js
  server/controllers/routes/admin/cohort/index.js
  server/controllers/routes/user/cohort/getSpecificCohort.js
  server/controllers/routes/user/cohort/index.js
  server/controllers/routes/user/index.js
  server/database/queries/cohort/getSpecificCohort.js
  server/database/queries/cohort/index.js
  server/database/queries/index.js
  test/index.test.js
Labels: Awaiting Review, Backend

#53 52 fix error, modify test script
  package.json
  server/app.js
  server/controllers/index.js
  server/controllers/middlewares/errorHandle/error.js
  server/controllers/middlewares/errorHandle/index.js
  test/index.test.js
Labels: Awaiting Review, Backend, priority-1

#45 make get /cohort route
  server/controllers/index.js
  server/controllers/routes/user/cohort/getCohortsData.js
  server/controllers/routes/user/cohort/index.js
  server/controllers/routes/user/index.js
  server/database/queries/cohort/getCohorts.js
  server/database/queries/cohort/index.js
  server/database/queries/index.js
  test/index.test.js
Labels: Awaiting Review, Backend

#49 23 put cohortid
  server/app.js
  server/controllers/index.js
  server/controllers/routes/admin/cohort/editCohort.js
  server/controllers/routes/admin/cohort/index.js
  server/controllers/routes/admin/index.js
  server/controllers/routes/user/cohort/getCohortsData.js
  server/controllers/routes/user/cohort/index.js
  server/controllers/routes/user/index.js
  server/database/queries/cohort/index.js
  server/database/queries/cohort/putSpecificCohort.js
  server/database/queries/index.js
  server/validation/editCohort.js
  server/validation/index.js
  test/index.test.js
Labels: Awaiting Review, Backend

#57 DELETE alumni/:studentId
  server/controllers/routes/admin/index.js
  server/controllers/routes/admin/student/deleteStudent.js
  server/controllers/routes/admin/student/index.js
  server/database/queries/index.js
  server/database/queries/student/deleteStudentQuery.js
  server/database/queries/student/index.js
  test/index.test.js
Labels: Awaiting Review, Backend

#56 GET cohort/project?type=
  server/controllers/routes/admin/index.js
  server/controllers/routes/admin/project/getCohortProjects.js
  server/controllers/routes/admin/project/index.js
  server/controllers/routes/user/cohort/getSpecificCohort.js
  server/controllers/routes/user/index.js
  server/database/config/fakeData.sql
  server/database/queries/index.js
  server/database/queries/project/getCohortProjects.js
  server/database/queries/project/index.js
  test/index.test.js
Labels: Awaiting Review, Backend

#48 add new cohort
  server/controllers/routes/admin/cohort/addCohort.js
  server/controllers/routes/admin/cohort/index.js
  server/controllers/routes/admin/index.js
  server/controllers/routes/user/project/getProjectById.js
  server/controllers/routes/user/project/index.js
  server/database/config/build.sql
  server/database/queries/cohort/index.js
  server/database/queries/cohort/postCohort.js
  server/database/queries/index.js
  server/validation/cohortSchema .js
  server/validation/index.js
  test/cohort.test.js
  test/index.test.js
Labels: Approved, Backend

#51 make DELETE project by id | Route
  client/.eslintrc.json
  server/controllers/index.js
  server/controllers/routes/admin/index.js
  server/controllers/routes/admin/project/deleteProjectData.js
  server/controllers/routes/admin/project/index.js
  server/controllers/routes/user/index.js
  server/database/queries/index.js
  server/database/queries/project/addProject.js
  server/database/queries/project/deleteProject.js
  server/database/queries/project/index.js
  test/index.test.js
Labels: Awaiting Review, Backend

#59 22 GET /projects/:projectId
  server/controllers/routes/user/index.js
  server/controllers/routes/user/project/getProjectById.js
  server/controllers/routes/user/project/index.js
  server/database/queries/index.js
  server/database/queries/project/getProjectById.js
  server/database/queries/project/index.js
  test/index.test.js
Labels: Awaiting Review, Backend

#60 25 PUT alumni/:studentId
  server/controllers/routes/admin/index.js
  server/controllers/routes/admin/student/index.js
  server/controllers/routes/admin/student/putStudentData.js
  server/database/queries/index.js
  server/database/queries/student/index.js
  server/database/queries/student/putStudent.js
  server/validation/index.js
  server/validation/studentSchema.js
  test/index.test.js
Labels: Approved, Backend

#50 12 GET projects?type=
  package.json
  server/controllers/routes/user/index.js
  server/controllers/routes/user/project/getProjectsByType.js
  server/controllers/routes/user/project/index.js
  server/database/queries/index.js
  server/database/queries/project/getProjectsByType.js
  server/database/queries/project/index.js
  test/index.test.js
Labels: Awaiting Review, Backend

#66 28 GET stats
  server/controllers/routes/admin/index.js
  server/controllers/routes/admin/stats.js
  server/database/queries/getStatsQuery.js
  server/database/queries/index.js
  test/index.test.js
Labels: Awaiting Review, Backend

#61 get alumin for cohort
  server/controllers/routes/user/index.js
  server/controllers/routes/user/student/getAlumniCohort.js
  server/controllers/routes/user/student/index.js
  server/database/queries/index.js
  server/database/queries/student/getSpecificAlumni.js
  server/database/queries/student/index.js
  test/index.test.js
Labels: Awaiting Review, Backend

#69 20 logout
  server/app.js
  server/controllers/routes/admin/index.js
  server/controllers/routes/admin/logout.js
Labels: Awaiting Review, Backend

#71 Logout route
  server/app.js
  server/controllers/routes/admin/index.js
  server/controllers/routes/admin/logout.js
Labels: Awaiting Review, Backend

#67 Get Alumni/studentId
  server/controllers/routes/admin/cohort/deleteCohort.js
  server/controllers/routes/admin/index.js
  server/controllers/routes/admin/project/addProject.js
  server/controllers/routes/admin/project/editProject.js
  server/controllers/routes/admin/project/getCohortProjects.js
  server/controllers/routes/admin/stats.js
  server/controllers/routes/user/index.js
  server/controllers/routes/user/project/getProjectsByType.js
  server/controllers/routes/user/student/getAlumni.js
  server/controllers/routes/user/student/getStudentById.js
  server/controllers/routes/user/student/index.js
  server/database/queries/index.js
  server/database/queries/student/getStudentByIdQuery.js
  server/database/queries/student/index.js
  server/validation/editCohort.js
  server/validation/generalSchema.js
  server/validation/index.js
  test/alumni.test.js
  test/cohort.test.js
  test/index.test.js
Labels: Awaiting Review, Backend

#68 13 post student route
  server/controllers/routes/admin/index.js
  server/controllers/routes/admin/student/addStudentData.js
  server/controllers/routes/admin/student/index.js
  server/database/queries/index.js
  server/database/queries/student/addStudent.js
  server/database/queries/student/index.js
  server/validation/studentSchema.js
  test/index.test.js
Labels: Awaiting Review, Backend

#72 POST login
  server/controllers/middlewares/auth/index.js
  server/controllers/routes/admin/index.js
  server/controllers/routes/admin/login.js
  server/controllers/routes/admin/logout.js
  server/database/config/fakeData.sql
  server/database/queries/cohort/getSpecificCohort.js
  server/database/queries/index.js
  server/database/queries/loginQuery.js
  server/validation/index.js
  server/validation/loginSchema.js
  test/alumni.test.js
  test/cohort.test.js
  test/index.test.js
Labels: Awaiting Review, Backend

#74 hanlde route /projects/:projectId/alumni
  server/controllers/routes/user/index.js
  server/controllers/routes/user/project/getStudentProject.js
  server/controllers/routes/user/project/index.js
  server/database/queries/index.js
  server/database/queries/project/index.js
  server/database/queries/project/studentProjectQuery.js
  test/index.test.js
Labels: Awaiting Review, Backend

#78 77 customize antd
  client/config-overrides.js
  client/lessVariables.js
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/app/style.css
  client/src/constants/routes.js
Labels: Awaiting Review, Frontend, priority-1

#92 90 admin card
  client/.eslintrc.json
  client/lessVariables.js
  client/src/app/style.css
  client/src/components/AdminCard/index.js
  client/src/components/AdminCard/style.css
  client/src/components/AdminContainer/style.css
Labels: Awaiting Review, Frontend, admin panel

#96 95 back end notes
  server/app.js
  server/controllers/admin/login.js
  server/routes/admin.js
Labels: Awaiting Review, Backend, priority-1

#91 79 login page
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/app/index.js
  client/src/assets/images/login-logo.png
  client/src/components/AdminContainer/index.js
  client/src/components/AdminContainer/style.css
  client/src/components/index.js
  client/src/containers/loginPage/index.js
  client/src/containers/loginPage/style.css
Labels: Done, Frontend, admin panel

#99 install babel-plugin-import as dependencies
  client/package-lock.json
  client/package.json
Labels: Awaiting Review, Frontend, priority-1

#93 86 add cohort
  client/.eslintrc.json
  client/src/app/index.js
  client/src/app/style.css
  client/src/components/Add-Edit-Form/index.js
  client/src/components/Add-Edit-Form/style.css
  client/src/containers/loginPage/index.js
  client/src/containers/loginPage/style.css
  server/controllers/admin/editCohort.js
  server/controllers/admin/editProject.js
  server/controllers/errorHandle/error.js
  test/cohort.test.js
Labels: Awaiting Review, Frontend

#94 Cohort Page
  client/package-lock.json
  client/package.json
  client/src/app/index.js
  client/src/components/AdminCard/index.js
  client/src/components/AdminCard/style.css
  client/src/components/AdminContainer/index.js
  client/src/components/AdminContainer/style.css
  client/src/containers/CohortPage/index.js
Labels: Awaiting Review, Frontend

#97 87 project page
  client/src/app/index.js
  client/src/components/AdminCard/index.js
  client/src/components/AdminCard/style.css
  client/src/components/AdminContainer/style.css
  client/src/constants/routes.js
  client/src/containers/AdminProjectPage/index.js
  server/database/data/fakeData.sql
Labels: Awaiting Review, Frontend, admin panel

#98 80 statistics page
  client/src/app/index.js
  client/src/containers/statisticsPage/index.js
  client/src/containers/statisticsPage/style.css
Labels: Done, Frontend, admin panel
