Repository GSG-G8/ca-wiki, pull requests merged in 2020-06, with the labels that each got.

#108 Pass logout props to Admin Container
  client/src/Contexts/LogoutContext.js
  client/src/app/index.js
  client/src/components/AdminContainer/index.js
  client/src/containers/AdminProjectPage/index.js
  client/src/containers/CohortPage/index.js
  client/src/containers/StudentPage/index.js
  client/src/containers/statisticsPage/index.js
Labels: Awaiting Review, Frontend, enhancement

#112 105 edit form
  client/src/components/Add-Edit-Form/index.js
  client/src/constants/routes.js
  client/src/containers/AdminProjectPage/index.js
Labels: Awaiting Review, Frontend, admin panel

#119 115 display back button
  client/package-lock.json
  client/src/components/AdminContainer/index.js
  client/src/components/AdminContainer/style.css
Labels: Awaiting Review, Frontend, admin panel

#110 Create page not found
  client/src/app/index.js
  client/src/assets/images/notFoundImg.jpg
  client/src/components/AdminContainer/index.js
  client/src/constants/routes.js
  client/src/containers/PageNotFound/index.js
  client/src/containers/PageNotFound/style.css
  client/src/containers/loginPage/index.js
Labels: Awaiting Review, Frontend

#129 User Container for all user pages
  client/src/app/index.js
  client/src/app/style.css
  client/src/components/ExamplePage/index.js
  client/src/components/ExamplePage/style.css
  client/src/components/UserContainer/index.js
  client/src/components/UserContainer/style.css
  client/src/constants/routes.js
Labels: Awaiting Review, Frontend

#126 contact us page
  client/package-lock.json
  client/package.json
  client/src/app/index.js
  client/src/components/UserContainer/index.js
  client/src/containers/ContactUsPage/index.js
  client/src/containers/ContactUsPage/style.css
Labels: Awaiting Review, Frontend

#127 Cohorts page
  client/package-lock.json
  client/package.json
  client/src/app/index.js
  client/src/components/CohortsAlumniPage/index.js
  client/src/components/CohortsAlumniPage/styles.css
  client/src/components/UserContainer/index.js
  client/src/components/UserContainer/style.css
  client/src/constants/routes.js
  client/src/containers/AdminCohortPage/index.js
  client/src/containers/AdminStudentPage/index.js
Labels: Awaiting Review, Frontend

#133 131 internal / remotely projects page
  client/package-lock.json
  client/src/app/index.js
  client/src/app/style.css
  client/src/components/AdminContainer/index.js
  client/src/components/AdminContainer/style.css
  client/src/components/CohortsAlumniPage/index.js
  client/src/components/ExamplePage/index.js
  client/src/components/UserContainer/index.js
  client/src/components/UserContainer/style.css
  client/src/constants/routes.js
  client/src/containers/AdminCohortPage/index.js
  client/src/containers/AdminProjectPage/index.js
  client/src/containers/AdminStudentPage/index.js
  client/src/containers/UserProjectPage/index.js
  client/src/containers/UserProjectPage/style.css
  server/database/data/fakeData.sql
Labels: Awaiting Review, Frontend

#134 Overview pages
  client/src/app/index.js
  client/src/components/ExamplePage/index.js
  client/src/components/ExamplePage/style.css
  client/src/components/OverviewComponent/index.js
  client/src/components/OverviewComponent/style.css
  client/src/containers/ClientsProjectsOverview/index.js
  client/src/containers/ContactUsPage/index.js
  client/src/containers/HomePage/index.js
  client/src/containers/InternalProjectsOverview/index.js
Labels: Approved, Frontend

#140 GET | Get alumnus projects data
  server/controllers/getStudentProjects.js
  server/controllers/index.js
  server/database/queries/index.js
  server/database/queries/student/getStudentProjects.js
  server/database/queries/student/index.js
  server/routes/alumni.js
  test/alumni.test.js
Labels: Awaiting Review, Backend, priority-1

#143 Assign projects to students
  server/controllers/admin/AssignProjectStudent.js
  server/controllers/admin/index.js
  server/controllers/index.js
  server/database/queries/index.js
  server/database/queries/student/AssignProjectStudentQuery.js
  server/database/queries/student/index.js
  server/routes/admin.js
  server/utils/index.js
  server/utils/validation/index.js
  server/utils/validation/studentProjectSchema.js
  test/alumni.test.js
Labels: Awaiting Review, Backend, priority-1

#144 135 project details
  client/src/app/index.js
  client/src/constants/routes.js
  client/src/containers/ProjectDetailsPage/index.js
  client/src/containers/ProjectDetailsPage/style.css
  server/database/data/fakeData.sql
  test/alumni.test.js
  test/index.test.js
Labels: Awaiting Review, Frontend

#137 130 search page
  client/src/app/index.js
  client/src/components/UserContainer/index.js
  client/src/components/UserContainer/style.css
  client/src/containers/SearchPage/index.js
  client/src/containers/SearchPage/style.css
Labels: Awaiting Review, Frontend

#148 fix bug in search page
  client/src/containers/SearchPage/index.js
Labels: Done, Frontend, bug, priority-1

#128 111 google analytics
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/app/index.js
  client/src/components/Charts/datepicker.js
  client/src/components/Charts/dayVisitsReport.js
  client/src/components/Charts/index.js
  client/src/components/Charts/pageviewReport.js
  client/src/components/Charts/queryReport.js
  client/src/components/Charts/utils.js
  client/src/containers/statisticsPage/index.js
  client/src/containers/statisticsPage/style.css
  client/src/googleAuth/authUtils.js
  client/src/googleAuth/signIn.js
  client/src/googleAuth/style.css
Labels: Awaiting Review, Frontend, admin panel

#151 fix bugs in NavLink
  client/src/components/UserContainer/index.js
Labels: Awaiting Review, Frontend, bug

#154 153 fix pug page not found
  client/src/app/index.js
  client/src/constants/routes.js
Labels: Done, Frontend, bug

#159 Handling protected route for secret env variables
  client/src/components/Charts/dayVisitsReport.js
  client/src/components/Charts/pageviewReport.js
  client/src/components/Charts/queryReport.js
  client/src/googleAuth/authUtils.js
  client/src/googleAuth/getSecrets.js
  server/controllers/admin/getSecret.js
  server/controllers/admin/index.js
  server/controllers/index.js
  server/routes/admin.js
Labels: Awaiting Review, Backend, Frontend, bug, priority-1

#163 fix bug in admin project page (github link)
  client/src/containers/AdminProjectPage/index.js
Labels: Done, Frontend, bug, priority-1

#165 fix bug in getStudentProjects.js query
  server/database/queries/student/getStudentProjects.js
Labels: Done, Frontend, bug, priority-1

#168 fix bug in main menu navigation
  client/src/containers/CohortProjectsPage/index.js
  client/src/containers/UserProjectPage/index.js
Labels: Done, Frontend, bug, priority-1

#166 make style for search page
  client/package-lock.json
  client/package.json
  client/src/containers/SearchPage/index.js
  client/src/containers/SearchPage/style.css
Labels: Awaiting Review, Frontend

#170 169 enhancement
  client/src/components/AdminContainer/index.js
  client/src/components/UserContainer/index.js
  client/src/containers/ProjectDetailsPage/index.js
  client/src/containers/SearchPage/style.css
Labels: Done, Frontend, enhancement

#172 171 loading page
  client/src/containers/AdminCohortPage/index.js
  client/src/containers/AdminProjectPage/index.js
  client/src/containers/AdminStudentPage/index.js
  client/src/containers/CohortProjectsPage/index.js
  client/src/containers/SearchPage/index.js
  client/src/containers/SpecificAlumnusPage/index.js
Labels: Awaiting Review, Frontend, enhancement

#176 edit home page content and the read me
  README.md
  client/src/containers/HomePage/index.js
Labels: Awaiting Review, Frontend

#175 173 fix bugs
  client/src/components/AdminContainer/index.js
  client/src/containers/CohortsAlumniPage/index.js
Labels: Done, Frontend, bug, priority-1

#161 149 style pages
  client/src/app/style.css
  client/src/components/Add-Edit-Form/index.js
  client/src/components/Add-Edit-Form/style.css
  client/src/components/AdminCard/index.js
  client/src/components/AdminCard/style.css
  client/src/components/AdminContainer/style.css
  client/src/components/OverviewComponent/index.js
  client/src/components/OverviewComponent/style.css
  client/src/components/UserContainer/index.js
  client/src/components/UserContainer/style.css
  client/src/containers/AdminProjectPage/index.js
  client/src/containers/AdminStudentPage/index.js
  client/src/containers/CohortProjectsPage/index.js
  client/src/containers/CohortProjectsPage/style.css
  client/src/containers/CohortsAlumniPage/index.js
  client/src/containers/CohortsAlumniPage/styles.css
  client/src/containers/ContactUsPage/index.js
  client/src/containers/ContactUsPage/style.css
  client/src/containers/ProjectDetailsPage/index.js
  client/src/containers/ProjectDetailsPage/style.css
  client/src/containers/SpecificAlumnusPage/index.js
  client/src/containers/SpecificAlumnusPage/style.css
  client/src/containers/UserProjectPage/style.css
  client/src/containers/statisticsPage/style.css
Labels: Frontend, in progress
