Repository GSG-G8/ca-wiki, pull requests merged in 2020-03, with the labels that each got.

#8 Project setup
  .eslintrc.json
  .gitignore
  client/.eslintrc.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/components/App/index.js
  client/src/components/App/style.css
  client/src/index.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/index.js
  server/controllers/middlewares/auth/index.js
  server/controllers/middlewares/errorHandle/index.js
  server/controllers/routes/admin/index.js
  server/controllers/routes/user/index.js
  server/controllers/utils/index.js
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/config/fakeData.sql
  server/database/queries/index.js
  server/index.js
  server/validation/index.js
  test/index.test.js
Labels: in progress

#30 DB setup
  .vscode/settings.json
  package.json
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/connection.js
Labels: Awaiting Review

#36 Configure Travis CI
  .travis.yml
  package.json
Labels: Awaiting Review, priority-1

#38 Express urlencoded middleware
  server/app.js
Labels: Awaiting Review

#34 fake dadata base
  server/database/config/fakeData.sql
Labels: Awaiting Review

#40 Edit file structure
  server/controllers/routes/admin/cohort/index.js
  server/controllers/routes/admin/project/index.js
  server/controllers/routes/admin/student/index.js
  server/controllers/routes/user/cohort/index.js
  server/controllers/routes/user/project/index.js
  server/controllers/routes/user/student/index.js
  server/database/queries/cohort/index.js
  server/database/queries/project/index.js
  server/database/queries/student/index.js
Labels: Awaiting Review, Backend, priority-1

#44 Client and server errors handling
  server/controllers/index.js
  server/controllers/middlewares/errorHandle/error.js
  server/controllers/middlewares/errorHandle/index.js
Labels: Approved, Awaiting Review, Backend
